In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/REIGN_2020_5.csv')

In [10]:
df['yearcode'] = df['ccode']*10000+df['year']

In [15]:
coupcount = df.groupby('yearcode').sum()

In [24]:
coup_agg = coupcount[['pt_attempt','pt_suc']]

In [28]:
coup_agg = coup_agg.reset_index()

In [69]:
coup_agg

        yearcode  pt_attempt  pt_suc
0        21950.0         0.0     0.0
1        21951.0         0.0     0.0
2        21952.0         0.0     0.0
3        21953.0         0.0     0.0
4        21954.0         0.0     0.0
...          ...         ...     ...
11298  9902016.0         0.0     0.0
11299  9902017.0         0.0     0.0
11300  9902018.0         0.0     0.0
11301  9902019.0         0.0     0.0
11302  9902020.0         0.0     0.0

[11303 rows x 3 columns]

In [27]:
yearly = df[df['month'] == 1]

In [86]:
yearly.columns

Index(['ccode', 'country', 'leader', 'year', 'month', 'elected', 'age', 'male',
       'militarycareer', 'tenure_months', 'government', 'anticipation',
       'ref_ant', 'leg_ant', 'exec_ant', 'irreg_lead_ant', 'election_now',
       'election_recent', 'leg_recent', 'exec_recent', 'lead_recent',
       'ref_recent', 'direct_recent', 'indirect_recent', 'victory_recent',
       'defeat_recent', 'change_recent', 'nochange_recent', 'delayed',
       'lastelection', 'loss', 'irregular', 'prev_conflict', 'pt_suc',
       'pt_attempt', 'precip', 'couprisk', 'pctile_risk', 'yearcode'],
      dtype='object')

In [57]:
coup_yearly = yearly.join(coup_agg, how = 'left', on = 'yearcode', rsuffix = '_year')

In [58]:
len(coup_yearly)

11369

In [59]:
coup_yearly

,ccode,country,leader,year,month,elected,age,male,militarycareer,tenure_months,...,prev_conflict,pt_suc,pt_attempt,precip,couprisk,pctile_risk,yearcode,yearcode_year,pt_attempt_year,pt_suc_year
0,2.0,USA,Truman,1950.0,1.0,1.0,66.0,1,0.0,58.0,...,0.0,0.0,0.0,-0.069058,NaN,NaN,21950.0,NaN,NaN,NaN
12,2.0,USA,Truman,1951.0,1.0,1.0,67.0,1,0.0,70.0,...,0.0,0.0,0.0,-0.202572,NaN,NaN,21951.0,NaN,NaN,NaN
24,2.0,USA,Truman,1952.0,1.0,1.0,68.0,1,0.0,82.0,...,0.0,0.0,0.0,0.394373,NaN,NaN,21952.0,NaN,NaN,NaN
36,2.0,USA,Truman,1953.0,1.0,1.0,69.0,1,0.0,94.0,...,0.0,0.0,0.0,-0.665329,NaN,NaN,21953.0,NaN,NaN,NaN
37,2.0,USA,Eisenhower,1953.0,1.0,1.0,63.0,1,1.0,1.0,...,0.0,0.0,0.0,-0.665329,NaN,NaN,21953.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135584,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2016.0,1.0,1.0,71.0,1,0.0,206.0,...,0.0,0.0,0.0,-0.391420,0.000374,0.262498,9902016.0,NaN,NaN,NaN
135596,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2017.0,1.0,1.0,72.0,1,0.0,218.0,...,0.0,0.0,0.0,0.025780,0.000236,0.116993,9902017.0,NaN,NaN,NaN
135608,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2018.0,1.0,1.0,73.0,1,0.0,230.0,...,0.0,0.0,0.0,0.278135,0.000265,0.147301,9902018.0,NaN,NaN,NaN
135620,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2019.0,1.0,1.0,74.0,1,0.0,242.0,...,0.0,0.0,0.0,0.210903,0.000261,0.143164,9902019.0,NaN,NaN,NaN
135632,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2020.0,1.0,1.0,75.0,1,0.0,254.0,...,0.0,0.0,0.0,-0.034972,0.000216,0.098266,9902020.0,NaN,NaN,NaN

In [60]:
len(coup_yearly)

11369

In [61]:
coup_yearly.columns

Index(['ccode', 'country', 'leader', 'year', 'month', 'elected', 'age', 'male',
       'militarycareer', 'tenure_months', 'government', 'anticipation',
       'ref_ant', 'leg_ant', 'exec_ant', 'irreg_lead_ant', 'election_now',
       'election_recent', 'leg_recent', 'exec_recent', 'lead_recent',
       'ref_recent', 'direct_recent', 'indirect_recent', 'victory_recent',
       'defeat_recent', 'change_recent', 'nochange_recent', 'delayed',
       'lastelection', 'loss', 'irregular', 'prev_conflict', 'pt_suc',
       'pt_attempt', 'precip', 'couprisk', 'pctile_risk', 'yearcode',
       'yearcode_year', 'pt_attempt_year', 'pt_suc_year'],
      dtype='object')

In [62]:
coup_yearly_drops = coup_yearly.drop(['pt_suc',
       'pt_attempt', 'couprisk', 'pctile_risk', 'yearcode_year'], axis =1 )

In [72]:
x = coup_yearly_drops.merge(coup_agg, on = 'yearcode')

In [81]:
x.drop(['pt_attempt_year','pt_suc_year'], axis = 1, inplace = True)

In [82]:
x[x['country']=='Argentina'].head(40)

,ccode,country,leader,year,month,elected,age,male,militarycareer,tenure_months,...,nochange_recent,delayed,lastelection,loss,irregular,prev_conflict,precip,yearcode,pt_attempt,pt_suc
2076,160.0,Argentina,Peron,1950.0,1.0,1.0,55.0,1,1.0,44.0,...,0.0,0.0,3.850147,3.850147,3.850147,0.0,-0.471071,1601950.0,0.0,0.0
2077,160.0,Argentina,Peron,1951.0,1.0,1.0,56.0,1,1.0,56.0,...,0.0,0.0,4.077538,4.077538,4.077538,0.0,-0.478472,1601951.0,1.0,0.0
2078,160.0,Argentina,Peron,1952.0,1.0,1.0,57.0,1,1.0,68.0,...,1.0,0.0,1.098612,4.262680,4.262680,0.0,-0.515629,1601952.0,0.0,0.0
2079,160.0,Argentina,Peron,1953.0,1.0,1.0,58.0,1,1.0,80.0,...,0.0,0.0,2.708050,4.418840,4.418840,0.0,-0.485485,1601953.0,0.0,0.0
2080,160.0,Argentina,Peron,1954.0,1.0,1.0,59.0,1,1.0,92.0,...,0.0,0.0,3.295837,4.553877,4.553877,0.0,-0.325525,1601954.0,0.0,0.0
2081,160.0,Argentina,Peron,1955.0,1.0,1.0,60.0,1,1.0,104.0,...,0.0,0.0,3.663562,4.672829,4.672829,0.0,-0.689384,1601955.0,3.0,2.0
2082,160.0,Argentina,Aramburu,1956.0,1.0,0.0,53.0,1,1.0,3.0,...,0.0,0.0,3.931826,4.779123,4.779123,0.0,-0.296160,1601956.0,1.0,0.0
2083,160.0,Argentina,Aramburu,1957.0,1.0,0.0,54.0,1,1.0,15.0,...,0.0,1.0,4.143135,4.875197,4.875197,0.0,-0.416696,1601957.0,0.0,0.0
2084,160.0,Argentina,Aramburu,1958.0,1.0,0.0,55.0,1,1.0,27.0,...,0.0,0.0,4.317488,4.962845,4.962845,0.0,0.325716,1601958.0,0.0,0.0
2085,160.0,Argentina,Frondizi,1959.0,1.0,1.0,51.0,1,0.0,9.0,...,0.0,0.0,2.484907,2.484907,2.484907,0.0,0.241938,1601959.0,0.0,0.0
2086,160.0,Argentina,Frondizi,1960.0,1.0,1.0,52.0,1,0.0,21.0,...,0.0,0.0,3.178054,3.178054,3.178054,0.0,0.384624,1601960.0,2.0,0.0
2087,160.0,Argentina,Frondizi,1961.0,1.0,1.0,53.0,1,0.0,33.0,...,0.0,0.0,3.583519,3.583519,3.583519,0.0,-0.554253,1601961.0,1.0,0.0
2088,160.0,Argentina,Frondizi,1962.0,1.0,1.0,54.0,1,0.0,45.0,...,0.0,0.0,3.871201,3.871201,3.871201,0.0,-0.101641,1601962.0,3.0,1.0
2089,160.0,Argentina,Guido,1963.0,1.0,0.0,53.0,1,0.0,11.0,...,0.0,0.0,4.094345,4.094345,4.094345,0.0,-1.393903,1601963.0,1.0,0.0
2090,160.0,Argentina,Arturo Illia,1964.0,1.0,1.0,64.0,1,0.0,4.0,...,0.0,0.0,1.945910,1.945910,4.276666,0.0,0.078103,1601964.0,0.0,0.0
2091,160.0,Argentina,Arturo Illia,1965.0,1.0,1.0,65.0,1,0.0,16.0,...,0.0,0.0,2.944439,2.944439,4.430817,0.0,-0.469340,1601965.0,0.0,0.0
2092,160.0,Argentina,Arturo Illia,1966.0,1.0,1.0,66.0,1,0.0,28.0,...,0.0,0.0,3.433987,3.433987,4.564348,0.0,-0.273491,1601966.0,1.0,1.0
2093,160.0,Argentina,Ongania,1967.0,1.0,0.0,53.0,1,1.0,8.0,...,0.0,0.0,3.761200,3.761200,4.682131,0.0,-0.315175,1601967.0,0.0,0.0
2094,160.0,Argentina,Ongania,1968.0,1.0,0.0,54.0,1,1.0,20.0,...,0.0,0.0,4.007333,4.007333,4.787492,0.0,-0.507752,1601968.0,0.0,0.0
2095,160.0,Argentina,Ongania,1969.0,1.0,0.0,55.0,1,1.0,32.0,...,0.0,0.0,4.204693,4.204693,4.882802,0.0,-0.796231,1601969.0,0.0,0.0
2096,160.0,Argentina,Ongania,1970.0,1.0,0.0,56.0,1,1.0,44.0,...,0.0,0.0,4.369448,4.369448,4.969813,0.0,-0.052380,1601970.0,1.0,1.0
2097,160.0,Argentina,Levingston,1971.0,1.0,0.0,51.0,1,1.0,8.0,...,0.0,0.0,4.510860,4.510860,5.049856,0.0,-0.775221,1601971.0,2.0,1.0
2098,160.0,Argentina,Lanusse,1972.0,1.0,0.0,54.0,1,1.0,11.0,...,0.0,0.0,4.634729,4.634729,5.123964,0.0,-0.801464,1601972.0,0.0,0.0
2099,160.0,Argentina,Lanusse,1973.0,1.0,0.0,55.0,1,1.0,23.0,...,0.0,0.0,4.744932,4.744932,5.192957,0.0,0.236089,1601973.0,0.0,0.0
2100,160.0,Argentina,Peron,1974.0,1.0,1.0,79.0,1,1.0,4.0,...,0.0,0.0,1.609438,2.397895,1.609438,0.0,0.313422,1601974.0,0.0,0.0
2101,160.0,Argentina,"Peron, Isabel",1975.0,1.0,0.0,44.0,0,0.0,7.0,...,0.0,0.0,2.833213,3.135494,2.833213,1.0,-0.423094,1601975.0,1.0,0.0
2102,160.0,Argentina,"Peron, Isabel",1976.0,1.0,0.0,45.0,0,0.0,19.0,...,0.0,0.0,3.367296,3.555348,3.367296,1.0,-0.120558,1601976.0,1.0,1.0
2103,160.0,Argentina,Videla,1977.0,1.0,0.0,52.0,1,1.0,11.0,...,0.0,0.0,3.713572,3.850147,3.713572,1.0,0.336036,1601977.0,0.0,0.0
2104,160.0,Argentina,Videla,1978.0,1.0,0.0,53.0,1,1.0,23.0,...,0.0,0.0,3.970292,4.077538,3.970292,0.0,0.361597,1601978.0,0.0,0.0
2105,160.0,Argentina,Videla,1979.0,1.0,0.0,54.0,1,1.0,35.0,...,0.0,0.0,4.174387,4.262680,4.174387,0.0,0.139591,1601979.0,0.0,0.0
2106,160.0,Argentina,Videla,1980.0,1.0,0.0,55.0,1,1.0,47.0,...,0.0,0.0,4.343805,4.418840,4.343805,0.0,-0.017567,1601980.0,0.0,0.0
2107,160.0,Argentina,Videla,1981.0,1.0,0.0,56.0,1,1.0,59.0,...,0.0,0.0,4.488637,4.553877,4.488637,0.0,0.882073,1601981.0,0.0,0.0
2108,160.0,Argentina,Galtieri,1982.0,1.0,0.0,56.0,1,1.0,2.0,...,0.0,0.0,4.615120,4.672829,4.615120,0.0,-0.181403,1601982.0,0.0,0.0
2109,160.0,Argentina,Bignone,1983.0,1.0,0.0,55.0,1,1.0,7.0,...,0.0,0.0,4.727388,4.779123,4.727388,0.0,0.650583,1601983.0,0.0,0.0
2110,160.0,Argentina,Alfonsin,1984.0,1.0,1.0,58.0,1,0.0,2.0,...,0.0,0.0,1.386294,1.386294,1.386294,0.0,-0.139496,1601984.0,0.0,0.0
2111,160.0,Argentina,Alfonsin,1985.0,1.0,1.0,59.0,1,0.0,14.0,...,0.0,0.0,2.772589,2.772589,2.772589,0.0,0.967381,1601985.0,0.0,0.0
2112,160.0,Argentina,Alfonsin,1986.0,1.0,1.0,60.0,1,0.0,26.0,...,0.0,0.0,3.332205,3.332205,3.332205,0.0,0.459708,1601986.0,0.0,0.0
2113,160.0,Argentina,Alfonsin,1987.0,1.0,1.0,61.0,1,0.0,38.0,...,0.0,0.0,3.688879,3.688879,3.688879,0.0,0.562282,1601987.0,0.0,0.0
2114,160.0,Argentina,Alfonsin,1988.0,1.0,1.0,62.0,1,0.0,50.0,...,0.0,0.0,3.951244,3.951244,3.951244,0.0,0.204022,1601988.0,1.0,0.0
2115,160.0,Argentina,Alfonsin,1989.0,1.0,1.0,63.0,1,0.0,62.0,...,0.0,0.0,4.158883,4.158883,4.158883,0.0,-1.559401,1601989.0,0.0,0.0

In [83]:
x['coupyear'] = x['pt_attempt'] > 0

In [87]:
x['coupsuc'] = x['pt_suc'] > 0

In [88]:
x

,ccode,country,leader,year,month,elected,age,male,militarycareer,tenure_months,...,lastelection,loss,irregular,prev_conflict,precip,yearcode,pt_attempt,pt_suc,coupyear,coupsuc
0,2.0,USA,Truman,1950.0,1.0,1.0,66.0,1,0.0,58.0,...,2.639057,5.327876,7.565793,0.0,-0.069058,21950.0,0.0,0.0,False,False
1,2.0,USA,Truman,1951.0,1.0,1.0,67.0,1,0.0,70.0,...,3.258097,5.384495,7.571989,0.0,-0.202572,21951.0,0.0,0.0,False,False
2,2.0,USA,Truman,1952.0,1.0,1.0,68.0,1,0.0,82.0,...,3.637586,5.438079,7.578145,0.0,0.394373,21952.0,0.0,0.0,False,False
3,2.0,USA,Truman,1953.0,1.0,1.0,69.0,1,0.0,94.0,...,1.098612,1.098612,7.584265,0.0,-0.665329,21953.0,0.0,0.0,False,False
4,2.0,USA,Eisenhower,1953.0,1.0,1.0,63.0,1,1.0,1.0,...,1.098612,1.098612,7.584265,0.0,-0.665329,21953.0,0.0,0.0,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11364,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2016.0,1.0,1.0,71.0,1,0.0,206.0,...,4.077538,5.817111,6.476973,0.0,-0.391420,9902016.0,0.0,0.0,False,False
11365,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2017.0,1.0,1.0,72.0,1,0.0,218.0,...,2.397895,5.852202,6.495265,0.0,0.025780,9902017.0,0.0,0.0,False,False
11366,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2018.0,1.0,1.0,73.0,1,0.0,230.0,...,3.135494,5.886104,6.513230,0.0,0.278135,9902018.0,0.0,0.0,False,False
11367,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2019.0,1.0,1.0,74.0,1,0.0,242.0,...,3.555348,5.918894,6.530878,0.0,0.210903,9902019.0,0.0,0.0,False,False
11368,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2020.0,1.0,1.0,75.0,1,0.0,254.0,...,3.850147,5.950643,6.548219,0.0,-0.034972,9902020.0,0.0,0.0,False,False

In [85]:
x['coupyear'].sum()

428

In [90]:
x= x.drop(['pt_attempt', 'pt_suc'], axis = 1)

In [92]:
x.to_pickle('../data/year_agg.pkl')

In [93]:
x_dummies = pd.get_dummies(x['government'])

In [94]:
x_dummies

,Dominant Party,Foreign/Occupied,Indirect Military,Military,Military-Personal,Monarchy,Oligarchy,Parliamentary Democracy,Party-Military,Party-Personal,Party-Personal-Military Hybrid,Personal Dictatorship,Presidential Democracy,Provisional - Civilian,Provisional - Military,Warlordism
0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11364,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
11365,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
11366,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
11367,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
11368,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0

In [95]:
x = x.join(x_dummies)

In [98]:
x = x.drop('Parliamentary Democracy', axis = 1)

In [99]:
x

,ccode,country,leader,year,month,elected,age,male,militarycareer,tenure_months,...,Monarchy,Oligarchy,Party-Military,Party-Personal,Party-Personal-Military Hybrid,Personal Dictatorship,Presidential Democracy,Provisional - Civilian,Provisional - Military,Warlordism
0,2.0,USA,Truman,1950.0,1.0,1.0,66.0,1,0.0,58.0,...,0,0,0,0,0,0,1,0,0,0
1,2.0,USA,Truman,1951.0,1.0,1.0,67.0,1,0.0,70.0,...,0,0,0,0,0,0,1,0,0,0
2,2.0,USA,Truman,1952.0,1.0,1.0,68.0,1,0.0,82.0,...,0,0,0,0,0,0,1,0,0,0
3,2.0,USA,Truman,1953.0,1.0,1.0,69.0,1,0.0,94.0,...,0,0,0,0,0,0,1,0,0,0
4,2.0,USA,Eisenhower,1953.0,1.0,1.0,63.0,1,1.0,1.0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11364,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2016.0,1.0,1.0,71.0,1,0.0,206.0,...,0,0,0,0,0,0,0,0,0,0
11365,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2017.0,1.0,1.0,72.0,1,0.0,218.0,...,0,0,0,0,0,0,0,0,0,0
11366,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2018.0,1.0,1.0,73.0,1,0.0,230.0,...,0,0,0,0,0,0,0,0,0,0
11367,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2019.0,1.0,1.0,74.0,1,0.0,242.0,...,0,0,0,0,0,0,0,0,0,0
11368,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2020.0,1.0,1.0,75.0,1,0.0,254.0,...,0,0,0,0,0,0,0,0,0,0

In [100]:
x.to_pickle('../data/year_agg_dum.pkl')