In [58]:
import pandas as pd
import pickle
import numpy as np

In [7]:
infile = open('reign_wb_dict','rb')
reign_wb_dict = pickle.load(infile)
infile.close()

In [5]:
df = pd.read_pickle('../data/year_agg.pkl')

In [6]:
df

,ccode,country,leader,year,month,elected,age,male,militarycareer,tenure_months,...,nochange_recent,delayed,lastelection,loss,irregular,prev_conflict,precip,yearcode,coupyear,coupsuc
0,2.0,USA,Truman,1950.0,1.0,1.0,66.0,1,0.0,58.0,...,0.0,0.0,2.639057,5.327876,7.565793,0.0,-0.069058,21950.0,False,False
1,2.0,USA,Truman,1951.0,1.0,1.0,67.0,1,0.0,70.0,...,0.0,0.0,3.258097,5.384495,7.571989,0.0,-0.202572,21951.0,False,False
2,2.0,USA,Truman,1952.0,1.0,1.0,68.0,1,0.0,82.0,...,0.0,0.0,3.637586,5.438079,7.578145,0.0,0.394373,21952.0,False,False
3,2.0,USA,Truman,1953.0,1.0,1.0,69.0,1,0.0,94.0,...,0.0,0.0,1.098612,1.098612,7.584265,0.0,-0.665329,21953.0,False,False
4,2.0,USA,Eisenhower,1953.0,1.0,1.0,63.0,1,1.0,1.0,...,0.0,0.0,1.098612,1.098612,7.584265,0.0,-0.665329,21953.0,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11364,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2016.0,1.0,1.0,71.0,1,0.0,206.0,...,0.0,0.0,4.077538,5.817111,6.476973,0.0,-0.391420,9902016.0,False,False
11365,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2017.0,1.0,1.0,72.0,1,0.0,218.0,...,0.0,0.0,2.397895,5.852202,6.495265,0.0,0.025780,9902017.0,False,False
11366,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2018.0,1.0,1.0,73.0,1,0.0,230.0,...,0.0,0.0,3.135494,5.886104,6.513230,0.0,0.278135,9902018.0,False,False
11367,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2019.0,1.0,1.0,74.0,1,0.0,242.0,...,0.0,0.0,3.555348,5.918894,6.530878,0.0,0.210903,9902019.0,False,False
11368,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2020.0,1.0,1.0,75.0,1,0.0,254.0,...,0.0,0.0,3.850147,5.950643,6.548219,0.0,-0.034972,9902020.0,False,False

In [9]:
def get_wb_name(val):
    return reign_wb_dict[val]

In [38]:
df['wb_name'] = df['ccode'].apply(get_wb_name)

In [17]:
reign_wb_dict[56] = "St. Lucia"

In [37]:
reign_wb_dict[817] = "Vietnam"

In [40]:
df

,ccode,country,leader,year,month,elected,age,male,militarycareer,tenure_months,...,delayed,lastelection,loss,irregular,prev_conflict,precip,yearcode,coupyear,coupsuc,wb_name
0,2.0,USA,Truman,1950.0,1.0,1.0,66.0,1,0.0,58.0,...,0.0,2.639057,5.327876,7.565793,0.0,-0.069058,21950.0,False,False,United States
1,2.0,USA,Truman,1951.0,1.0,1.0,67.0,1,0.0,70.0,...,0.0,3.258097,5.384495,7.571989,0.0,-0.202572,21951.0,False,False,United States
2,2.0,USA,Truman,1952.0,1.0,1.0,68.0,1,0.0,82.0,...,0.0,3.637586,5.438079,7.578145,0.0,0.394373,21952.0,False,False,United States
3,2.0,USA,Truman,1953.0,1.0,1.0,69.0,1,0.0,94.0,...,0.0,1.098612,1.098612,7.584265,0.0,-0.665329,21953.0,False,False,United States
4,2.0,USA,Eisenhower,1953.0,1.0,1.0,63.0,1,1.0,1.0,...,0.0,1.098612,1.098612,7.584265,0.0,-0.665329,21953.0,False,False,United States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11364,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2016.0,1.0,1.0,71.0,1,0.0,206.0,...,0.0,4.077538,5.817111,6.476973,0.0,-0.391420,9902016.0,False,False,American Samoa
11365,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2017.0,1.0,1.0,72.0,1,0.0,218.0,...,0.0,2.397895,5.852202,6.495265,0.0,0.025780,9902017.0,False,False,American Samoa
11366,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2018.0,1.0,1.0,73.0,1,0.0,230.0,...,0.0,3.135494,5.886104,6.513230,0.0,0.278135,9902018.0,False,False,American Samoa
11367,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2019.0,1.0,1.0,74.0,1,0.0,242.0,...,0.0,3.555348,5.918894,6.530878,0.0,0.210903,9902019.0,False,False,American Samoa
11368,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2020.0,1.0,1.0,75.0,1,0.0,254.0,...,0.0,3.850147,5.950643,6.548219,0.0,-0.034972,9902020.0,False,False,American Samoa

In [42]:
reign_wb_dict_update = reign_wb_dict

In [44]:
filename = 'reign_wb_dict_update'
outfile = open(filename,'wb')
pickle.dump(reign_wb_dict_update,outfile)
outfile.close()

In [45]:
inv_dict = {v: k for k, v in reign_wb_dict_update.items()}

In [46]:
inv_dict

{'Afghanistan': 700.0,
 'Angola': 540.0,
 'Albania': 339.0,
 'Andorra': 232.0,
 'United Arab Emirates': 696.0,
 'Argentina': 160.0,
 'Armenia': 371.0,
 'Antigua and Barbuda': 58.0,
 'Australia': 900.0,
 'Austria': 305.0,
 'Azerbaijan': 373.0,
 'Burundi': 516.0,
 'Belgium': 211.0,
 'Benin': 434.0,
 'Burkina Faso': 439.0,
 'Bangladesh': 771.0,
 'Bulgaria': 355.0,
 'Bahrain': 692.0,
 'Belarus': 370.0,
 'Belize': 80.0,
 'Bolivia': 145.0,
 'Brazil': 140.0,
 'Barbados': 53.0,
 'Brunei': 835.0,
 'Bhutan': 760.0,
 'Botswana': 571.0,
 'Canada': 20.0,
 'Switzerland': 225.0,
 'Chile': 155.0,
 'China': 710.0,
 'Cameroon': 471.0,
 'Colombia': 100.0,
 'Comoros': 581.0,
 'Costa Rica': 94.0,
 'Cuba': 40.0,
 'Cyprus': 352.0,
 'Germany': 265,
 'Djibouti': 522.0,
 'Dominica': 54.0,
 'Denmark': 390.0,
 'Dominican Republic': 42.0,
 'Algeria': 615.0,
 'Ecuador': 130.0,
 'Egypt': 651.0,
 'Eritrea': 531.0,
 'Spain': 230.0,
 'Estonia': 366.0,
 'Ethiopia': 530.0,
 'Finland': 375.0,
 'Fiji': 950.0,
 'France': 220.0,
 'Micronesia': 987.0,
 'Gabon': 481.0,
 'Georgia': 372.0,
 'Ghana': 452.0,
 'Guinea': 438.0,
 'Equatorial Guinea': 411.0,
 'Greece': 350.0,
 'Grenada': 55.0,
 'Guatemala': 90.0,
 'Guyana': 110.0,
 'Honduras': 91.0,
 'Croatia': 344.0,
 'Haiti': 41.0,
 'Hungary': 310.0,
 'Indonesia': 850.0,
 'India': 750.0,
 'Ireland': 205.0,
 'Iran': 630.0,
 'Iraq': 645.0,
 'Iceland': 395.0,
 'Israel': 666.0,
 'Italy': 325.0,
 'Jamaica': 51.0,
 'Jordan': 663.0,
 'Japan': 740.0,
 'Kazakhstan': 705.0,
 'Kenya': 501.0,
 'Cambodia': 811.0,
 'Kiribati': 946.0,
 'Kuwait': 690.0,
 'Lebanon': 660.0,
 'Liberia': 450.0,
 'Libya': 620.0,
 'Liechtenstein': 223.0,
 'Sri Lanka': 780.0,
 'Lesotho': 570.0,
 'Lithuania': 368.0,
 'Luxembourg': 212.0,
 'Latvia': 367.0,
 'Morocco': 600.0,
 'Monaco': 221.0,
 'Moldova': 359.0,
 'Madagascar': 580.0,
 'Maldives': 781.0,
 'Mexico': 70.0,
 'Marshall Islands': 983.0,
 'Mali': 432.0,
 'Malta': 338.0,
 'Myanmar': 775.0,
 'Montenegro': 341.0,
 'Mongolia': 712.0,
 'Mozambique': 541.0,
 'Mauritania': 435.0,
 'Mauritius': 590.0,
 'Malawi': 553.0,
 'Malaysia': 820.0,
 'Namibia': 565.0,
 'Niger': 436.0,
 'Nigeria': 475.0,
 'Nicaragua': 93.0,
 'Netherlands': 210.0,
 'Norway': 385.0,
 'Nepal': 790.0,
 'Nauru': 970.0,
 'New Zealand': 920.0,
 'Oman': 698.0,
 'Pakistan': 770.0,
 'Panama': 95.0,
 'Peru': 135.0,
 'Philippines': 840.0,
 'Palau': 986.0,
 'Papua New Guinea': 910.0,
 'Poland': 290.0,
 'Portugal': 235.0,
 'Paraguay': 150.0,
 'Qatar': 694.0,
 'Romania': 360.0,
 'Russia': 365.0,
 'Rwanda': 517.0,
 'Saudi Arabia': 670.0,
 'Sudan': 625.0,
 'Senegal': 433.0,
 'Singapore': 830.0,
 'Solomon Islands': 940.0,
 'Sierra Leone': 451.0,
 'El Salvador': 92.0,
 'San Marino': 331.0,
 'Somalia': 520.0,
 'Serbia': 345.0,
 'South Sudan': 626.0,
 'Suriname': 115.0,
 'Slovenia': 349.0,
 'Sweden': 380.0,
 'Seychelles': 591.0,
 'Chad': 483.0,
 'Togo': 461.0,
 'Thailand': 800.0,
 'Tajikistan': 702.0,
 'Turkmenistan': 701.0,
 'Tonga': 955.0,
 'Trinidad and Tobago': 52.0,
 'Tunisia': 616.0,
 'Turkey': 640.0,
 'Tuvalu': 947.0,
 'Tanzania': 510.0,
 'Uganda': 500.0,
 'Ukraine': 369.0,
 'Uruguay': 165.0,
 'Uzbekistan': 704.0,
 'Venezuela': 101.0,
 'Vietnam': 817,
 'Vanuatu': 935.0,
 'American Samoa': 990.0,
 'Kosovo': 347.0,
 'Yemen': 680,
 'South Africa': 560.0,
 'Zambia': 551.0,
 'Zimbabwe': 552.0,
 'United States': 2.0,
 'The Bahamas': 31.0,
 'Bosnia and Herzegovina': 346.0,
 'Central African Republic': 482.0,
 "Côte d'Ivoire": 437.0,
 'Dem. Rep. Congo': 490.0,
 'Czech Republic': 315,
 'Congo': 484.0,
 'Cabo Verde': 402.0,
 'United Kingdom': 200.0,
 'The Gambia': 420.0,
 'Guinea-Bissau': 404.0,
 'Kyrgyz Republic': 703.0,
 'Korea': 732.0,
 "Dem. People's Rep. Korea": 731.0,
 'São Tomé and Principe': 403.0,
 'Slovak Republic': 317.0,
 'St. Kitts and Nevis': 60.0,
 'Lao PDR': 812,
 'Syrian Arab Republic': 652,
 'St. Vincent and the Grenadines': 57,
 'Timor-Leste': 860,
 'St. Lucia': 56,
 'Macedonia': 343,
 'Eswatini': 572}

In [47]:
filename = 'inv_dict'
outfile = open(filename,'wb')
pickle.dump(inv_dict,outfile)
outfile.close()

In [51]:
wb_gdpg = pd.read_csv('../data/wb_gdp.csv', delimiter='\t')

In [59]:
years = np.arange(1960, 2020)

In [60]:
years

array([1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970,
       1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981,
       1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992,
       1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
       2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014,
       2015, 2016, 2017, 2018, 2019])

In [81]:
wb_gdpg.T

,0,1,2,3,4,5,6,7,8,9,...,254,255,256,257,258,259,260,261,262,263
Country Name,Aruba,Afghanistan,Angola,Albania,Andorra,Arab World,United Arab Emirates,Argentina,Armenia,American Samoa,...,Virgin Islands (U.S.),Vietnam,Vanuatu,World,Samoa,Kosovo,"Yemen, Rep.",South Africa,Zambia,Zimbabwe
Country Code,ABW,AFG,AGO,ALB,AND,ARB,ARE,ARG,ARM,ASM,...,VIR,VNM,VUT,WLD,WSM,XKX,YEM,ZAF,ZMB,ZWE
Indicator Name,GDP growth (annual %),GDP growth (annual %),GDP growth (annual %),GDP growth (annual %),GDP growth (annual %),GDP growth (annual %),GDP growth (annual %),GDP growth (annual %),GDP growth (annual %),GDP growth (annual %),...,GDP growth (annual %),GDP growth (annual %),GDP growth (annual %),GDP growth (annual %),GDP growth (annual %),GDP growth (annual %),GDP growth (annual %),GDP growth (annual %),GDP growth (annual %),GDP growth (annual %)
Indicator Code,NY.GDP.MKTP.KD.ZG,NY.GDP.MKTP.KD.ZG,NY.GDP.MKTP.KD.ZG,NY.GDP.MKTP.KD.ZG,NY.GDP.MKTP.KD.ZG,NY.GDP.MKTP.KD.ZG,NY.GDP.MKTP.KD.ZG,NY.GDP.MKTP.KD.ZG,NY.GDP.MKTP.KD.ZG,NY.GDP.MKTP.KD.ZG,...,NY.GDP.MKTP.KD.ZG,NY.GDP.MKTP.KD.ZG,NY.GDP.MKTP.KD.ZG,NY.GDP.MKTP.KD.ZG,NY.GDP.MKTP.KD.ZG,NY.GDP.MKTP.KD.ZG,NY.GDP.MKTP.KD.ZG,NY.GDP.MKTP.KD.ZG,NY.GDP.MKTP.KD.ZG,NY.GDP.MKTP.KD.ZG
1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015,-0.450586,1.45131,0.943576,2.21875,0.842204,3.30635,5.10594,2.73116,3.2,1.40406,...,0.194175,6.67929,0.2,2.85726,4.27219,4.09528,-16.6785,1.19373,2.91988,1.77987
2016,-0.211225,2.26031,-2.5801,3.3148,1.88912,3.37262,3.06096,-2.08033,0.2,-2.76923,...,0.904393,6.21081,3.5,2.58512,8.05416,4.07029,-13.6215,0.399088,3.75718,0.755869
2017,1.33051,2.66529,-0.147207,3.82108,1.72402,0.832435,0.490861,2.66859,7.5,-5.85443,...,-1.69654,6.81225,4.4,3.19656,1.01556,4.22609,-5.94232,1.41451,3.40317,4.70404
2018,NaN,1.03066,-2.13349,4.14524,1.62935,2.04598,1.72635,-2.48179,5.2,2.18487,...,NaN,7.07579,3.2,3.05839,-2.1681,3.81331,-2.70147,0.787056,3.7949,6.15919
2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [76]:
wb_gdpg.pivot?

In [53]:
wb_gdpg.pivot(index='Country Name', columns='Indicator Name')

,Country Code,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Indicator Name,GDP growth (annual %),GDP growth (annual %),GDP growth (annual %),GDP growth (annual %),GDP growth (annual %),GDP growth (annual %),GDP growth (annual %),GDP growth (annual %),GDP growth (annual %),GDP growth (annual %),...,GDP growth (annual %),GDP growth (annual %),GDP growth (annual %),GDP growth (annual %),GDP growth (annual %),GDP growth (annual %),GDP growth (annual %),GDP growth (annual %),GDP growth (annual %),GDP growth (annual %)
Country Name,,,,,,,,,,,,,,,,,,,,,
Afghanistan,AFG,NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.362441,0.426355,12.752287,5.600745,2.724543,1.451315,2.260314,2.665292,1.030660,NaN
Albania,ALB,NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.706891,2.545323,1.417524,1.001989,1.774487,2.218751,3.314805,3.821081,4.145238,NaN
Algeria,DZA,NY.GDP.MKTP.KD.ZG,NaN,-13.605441,-19.685042,34.313729,5.839413,6.206898,-4.804971,9.452963,...,3.600000,2.900000,3.400000,2.800000,3.800000,3.700000,3.200000,1.300000,1.400000,NaN
American Samoa,ASM,NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.442478,0.293686,-4.392387,-2.756508,0.944882,1.404056,-2.769231,-5.854430,2.184874,NaN
Andorra,AND,NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-5.358826,-4.646543,-1.615218,0.351645,2.277683,0.842204,1.889124,1.724022,1.629345,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
West Bank and Gaza,PSE,NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.099089,12.413636,6.284236,2.217422,-0.181891,3.428732,4.708435,3.140237,0.905278,NaN
World,WLD,NY.GDP.MKTP.KD.ZG,NaN,4.300340,5.553578,5.353422,6.714787,5.519477,5.769478,4.486744,...,4.299175,3.132457,2.507626,2.655492,2.835050,2.857257,2.585116,3.196562,3.058395,NaN
"Yemen, Rep.",YEM,NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.702307,-12.714897,2.392990,4.823519,-0.188690,-16.678463,-13.621458,-5.942320,-2.701475,NaN
Zambia,ZMB,NY.GDP.MKTP.KD.ZG,NaN,1.361382,-2.490839,3.272393,12.214048,16.647456,-5.570310,7.919697,...,10.298206,5.564625,7.597617,5.059376,4.695826,2.919881,3.757178,3.403169,3.794901,NaN
Zimbabwe,ZWE,NY.GDP.MKTP.KD.ZG,NaN,6.316157,1.434471,6.244345,-1.106172,4.910571,1.523130,8.367009,...,19.675323,14.193913,16.665429,1.989493,2.376929,1.779873,0.755869,4.704035,6.159190,NaN