In [1]:
import pandas as pd

In [23]:
year_agg = pd.read_pickle('../data/year_agg.pkl')

In [24]:
nmc_df = pd.read_csv('../data/NMC_5_0.csv')
trade_df = pd.read_csv('../data/COW_trade_3.0/national_trade_3.0.csv')

In [25]:
nmc_df['yearcode'] = nmc_df['ccode']*10000 + nmc_df['year']
trade_df['yearcode'] = trade_df['ccode']*10000 + trade_df['year']

In [26]:
nmc_df

,stateabb,ccode,year,milex,milper,irst,pec,tpop,upop,cinc,version,yearcode
0,USA,2,1816,3823,17,80,254,8659.0,101.0,0.039698,2011,21816
1,USA,2,1817,2466,15,80,277,8899.0,106.0,0.035817,2011,21817
2,USA,2,1818,1910,14,90,302,9139.0,112.0,0.036126,2011,21818
3,USA,2,1819,2301,13,90,293,9379.0,118.0,0.037133,2011,21819
4,USA,2,1820,1556,15,110,303,9618.0,124.0,0.037087,2011,21820
...,...,...,...,...,...,...,...,...,...,...,...,...
15166,WSM,990,2008,0,0,0,39,183.0,0.0,0.000005,2011,9902008
15167,WSM,990,2009,0,0,0,38,185.0,0.0,0.000005,2011,9902009
15168,WSM,990,2010,0,0,0,38,186.0,0.0,0.000005,2011,9902010
15169,WSM,990,2011,0,0,0,38,187.0,0.0,0.000005,2011,9902011
15170,WSM,990,2012,0,0,0,38,189.0,0.0,0.000005,2011,9902012

In [27]:
year_agg

,ccode,country,leader,year,month,elected,age,male,militarycareer,tenure_months,...,nochange_recent,delayed,lastelection,loss,irregular,prev_conflict,precip,yearcode,coupyear,coupsuc
0,2.0,USA,Truman,1950.0,1.0,1.0,66.0,1,0.0,58.0,...,0.0,0.0,2.639057,5.327876,7.565793,0.0,-0.069058,21950.0,False,False
1,2.0,USA,Truman,1951.0,1.0,1.0,67.0,1,0.0,70.0,...,0.0,0.0,3.258097,5.384495,7.571989,0.0,-0.202572,21951.0,False,False
2,2.0,USA,Truman,1952.0,1.0,1.0,68.0,1,0.0,82.0,...,0.0,0.0,3.637586,5.438079,7.578145,0.0,0.394373,21952.0,False,False
3,2.0,USA,Truman,1953.0,1.0,1.0,69.0,1,0.0,94.0,...,0.0,0.0,1.098612,1.098612,7.584265,0.0,-0.665329,21953.0,False,False
4,2.0,USA,Eisenhower,1953.0,1.0,1.0,63.0,1,1.0,1.0,...,0.0,0.0,1.098612,1.098612,7.584265,0.0,-0.665329,21953.0,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11364,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2016.0,1.0,1.0,71.0,1,0.0,206.0,...,0.0,0.0,4.077538,5.817111,6.476973,0.0,-0.391420,9902016.0,False,False
11365,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2017.0,1.0,1.0,72.0,1,0.0,218.0,...,0.0,0.0,2.397895,5.852202,6.495265,0.0,0.025780,9902017.0,False,False
11366,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2018.0,1.0,1.0,73.0,1,0.0,230.0,...,0.0,0.0,3.135494,5.886104,6.513230,0.0,0.278135,9902018.0,False,False
11367,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2019.0,1.0,1.0,74.0,1,0.0,242.0,...,0.0,0.0,3.555348,5.918894,6.530878,0.0,0.210903,9902019.0,False,False
11368,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2020.0,1.0,1.0,75.0,1,0.0,254.0,...,0.0,0.0,3.850147,5.950643,6.548219,0.0,-0.034972,9902020.0,False,False

In [28]:
joint_df = year_agg.join(trade_df.set_index('yearcode'), on='yearcode', how = 'inner', rsuffix = '_tradedf' )
df = joint_df.join(nmc_df.set_index('yearcode'), on='yearcode', how = 'inner', rsuffix = '_nmcdf' )

In [29]:
df

,ccode,country,leader,year,month,elected,age,male,militarycareer,tenure_months,...,ccode_nmcdf,year_nmcdf,milex,milper,irst,pec,tpop,upop,cinc,version_nmcdf
0,2.0,USA,Truman,1950.0,1.0,1.0,66.0,1,0.0,58.0,...,2,1950,14559000,1460,87848,1241836,152271.0,43964.0,0.284443,2011
1,2.0,USA,Truman,1951.0,1.0,1.0,67.0,1,0.0,70.0,...,2,1951,33398000,3249,95435,1325948,154878.0,44711.0,0.319499,2011
2,2.0,USA,Truman,1952.0,1.0,1.0,68.0,1,0.0,82.0,...,2,1952,47852000,3636,84520,1309824,157553.0,45123.0,0.311367,2011
3,2.0,USA,Truman,1953.0,1.0,1.0,69.0,1,0.0,94.0,...,2,1953,49621008,3555,101250,1347597,160184.0,46581.0,0.311158,2011
4,2.0,USA,Eisenhower,1953.0,1.0,1.0,63.0,1,1.0,1.0,...,2,1953,49621008,3555,101250,1347597,160184.0,46581.0,0.311158,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11353,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2005.0,1.0,1.0,60.0,1,0.0,74.0,...,990,2005,0,0,0,37,180.0,0.0,0.000005,2011
11354,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2006.0,1.0,1.0,61.0,1,0.0,86.0,...,990,2006,0,0,0,38,181.0,0.0,0.000005,2011
11355,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2007.0,1.0,1.0,62.0,1,0.0,98.0,...,990,2007,0,0,0,40,182.0,0.0,0.000005,2011
11356,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2008.0,1.0,1.0,63.0,1,0.0,110.0,...,990,2008,0,0,0,39,183.0,0.0,0.000005,2011
11357,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2009.0,1.0,1.0,64.0,1,0.0,122.0,...,990,2009,0,0,0,38,185.0,0.0,0.000005,2011

In [30]:
df['pt_attempt'] = df['coupyear']

In [31]:
df['pt_suc'] = df['coupsuc']

In [32]:
df = df.drop(['coupyear', 'coupsuc'], axis =1)

In [16]:
df.to_pickle('../data/yearly_nmc_trade.pkl')

In [33]:
df

,ccode,country,leader,year,month,elected,age,male,militarycareer,tenure_months,...,milex,milper,irst,pec,tpop,upop,cinc,version_nmcdf,pt_attempt,pt_suc
0,2.0,USA,Truman,1950.0,1.0,1.0,66.0,1,0.0,58.0,...,14559000,1460,87848,1241836,152271.0,43964.0,0.284443,2011,False,False
1,2.0,USA,Truman,1951.0,1.0,1.0,67.0,1,0.0,70.0,...,33398000,3249,95435,1325948,154878.0,44711.0,0.319499,2011,False,False
2,2.0,USA,Truman,1952.0,1.0,1.0,68.0,1,0.0,82.0,...,47852000,3636,84520,1309824,157553.0,45123.0,0.311367,2011,False,False
3,2.0,USA,Truman,1953.0,1.0,1.0,69.0,1,0.0,94.0,...,49621008,3555,101250,1347597,160184.0,46581.0,0.311158,2011,False,False
4,2.0,USA,Eisenhower,1953.0,1.0,1.0,63.0,1,1.0,1.0,...,49621008,3555,101250,1347597,160184.0,46581.0,0.311158,2011,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11353,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2005.0,1.0,1.0,60.0,1,0.0,74.0,...,0,0,0,37,180.0,0.0,0.000005,2011,False,False
11354,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2006.0,1.0,1.0,61.0,1,0.0,86.0,...,0,0,0,38,181.0,0.0,0.000005,2011,False,False
11355,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2007.0,1.0,1.0,62.0,1,0.0,98.0,...,0,0,0,40,182.0,0.0,0.000005,2011,False,False
11356,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2008.0,1.0,1.0,63.0,1,0.0,110.0,...,0,0,0,39,183.0,0.0,0.000005,2011,False,False
11357,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2009.0,1.0,1.0,64.0,1,0.0,122.0,...,0,0,0,38,185.0,0.0,0.000005,2011,False,False

In [34]:
dummies = pd.get_dummies(df['government'])
df_dumb = df.join(dummies)
drop_list = ['yearcode', 'country_tradedf', 'year_tradedf', 'alt_imports', 'alt_exports', 'source1', 'source2',
       'version', 'stateabb', 'ccode_nmcdf', 'year_nmcdf', 'version_nmcdf', 'tpop', 'ccode_tradedf', 'Parliamentary Democracy']
df = df_dumb.drop(drop_list, axis = 1)

In [35]:
df

,ccode,country,leader,year,month,elected,age,male,militarycareer,tenure_months,...,Monarchy,Oligarchy,Party-Military,Party-Personal,Party-Personal-Military Hybrid,Personal Dictatorship,Presidential Democracy,Provisional - Civilian,Provisional - Military,Warlordism
0,2.0,USA,Truman,1950.0,1.0,1.0,66.0,1,0.0,58.0,...,0,0,0,0,0,0,1,0,0,0
1,2.0,USA,Truman,1951.0,1.0,1.0,67.0,1,0.0,70.0,...,0,0,0,0,0,0,1,0,0,0
2,2.0,USA,Truman,1952.0,1.0,1.0,68.0,1,0.0,82.0,...,0,0,0,0,0,0,1,0,0,0
3,2.0,USA,Truman,1953.0,1.0,1.0,69.0,1,0.0,94.0,...,0,0,0,0,0,0,1,0,0,0
4,2.0,USA,Eisenhower,1953.0,1.0,1.0,63.0,1,1.0,1.0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11353,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2005.0,1.0,1.0,60.0,1,0.0,74.0,...,0,0,0,0,0,0,0,0,0,0
11354,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2006.0,1.0,1.0,61.0,1,0.0,86.0,...,0,0,0,0,0,0,0,0,0,0
11355,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2007.0,1.0,1.0,62.0,1,0.0,98.0,...,0,0,0,0,0,0,0,0,0,0
11356,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2008.0,1.0,1.0,63.0,1,0.0,110.0,...,0,0,0,0,0,0,0,0,0,0
11357,990.0,Samoa,Tuilaepa Sailele Malielegaoi,2009.0,1.0,1.0,64.0,1,0.0,122.0,...,0,0,0,0,0,0,0,0,0,0

In [36]:
df.to_pickle('../data/yearly_nmc_trade.pkl')